#!/bin/sh

IN_DIR=input
OUT_DIR=output
EXP_DIR=expected

for IN_F in $IN_DIR/*.txt ; do
  BASE=`basename $IN_F`
  if [ $BASE == "tutorial.txt" -o $BASE == "reference.txt" ] ; then
    continue
  fi
  F_BASE=${BASE/.txt}
  python mkpydoc.py $IN_F $OUT_DIR/$F_BASE.tex
  diff -s -u $EXP_DIR/$F_BASE.tex $OUT_DIR/$F_BASE.tex
done


