 # -*- coding: UTF8 -*-

att_set_dict = {
'abstract-block':['abstract-block', 'block'],
'abstract-paragraph-block':['abstract-paragraph-block', 'block'],
'abstract-title-block':['abstract-title-block', 'block'],
'address-value-block':['address-value-block', 'block'],
'admonition-custom-block':['admonition-custom-block', 'block'],
'admonition-custorm-title-block':['admonition-custorm-title-block', 'block'],
'admonition-first-paragraph-block':['admonition-first-paragraph-block', 'block'],
'admonition-paragraph-block':['admonition-paragraph-block', 'block'],
'attention-block':['attention-block', 'block'],
'attention-title-block':['attention-title-block', 'block'],
'basic-link-inline':['basic-link-inline', 'inline'],
'bibliographic-fields-block':['bibliographic-fields-block', 'block'],
'bibliographic-fields-front-list-block':['bibliographic-fields-front-list-block', 'list-block'],
'bibliographic-fields-item-body':['bibliographic-fields-item-body', 'item-body'],
'bibliographic-fields-item-label-block':['bibliographic-fields-item-label-block', 'block'],
'bibliographic-fields-list-block':['bibliographic-fields-list-block', 'list-block'],
'bibliographic-fields-list-item':['bibliographic-fields-list-item', 'list-item'],
'bibliographic-fields-list-item-label':['bibliographic-fields-list-item-label', 'item-label'],
'block-quote-attribution-block':['block-quote-attribution-block', 'block'],
'block-quote-first-paragraph-block':['block-quote-first-paragraph-block', 'block'],
'block-quote-outer-block':['block-quote-outer-block', 'block'],
'block-quote-paragraph-block':['block-quote-paragraph-block', 'block'],
'body-flow':['body-flow', 'flow'],
'body-page-sequence':['body-page-sequence', 'page-sequence'],
'body-simple-page-master':['body-simple-page-master', 'simple-page-master'],
'bullet-first-list-item':['bullet-first-list-item', 'list-item'],
'bullet-level2-list-block':['bullet-level2-list-block', 'list-block'],
'bullet-list-block':['bullet-list-block', 'list-block'],
'bullet-list-item':['bullet-list-item', 'list-item'],
'bullet-list-item-body':['bullet-list-item-body', 'item-body'],
'bullet-list-item-body-block':['bullet-list-item-body-block', 'block'],
'bullet-list-item-label':['bullet-list-item-label', 'item-label'],
'bullet-list-item-label-block':['bullet-list-item-label-block', 'block'],
'caption-block':['caption-block', 'block'],
'caution-block':['caution-block', 'block'],
'caution-title-block':['caution-title-block', 'block'],
'cell-block':['cell-block', 'block'],
'classifier-inline':['classifier-inline', 'inline'],
'container-first-paragraph-block':['container-first-paragraph-block', 'block'],
'container-outer-block':['container-outer-block', 'block'],
'container-paragraph-block':['container-paragraph-block', 'block'],
'danger-block':['danger-block', 'block'],
'danger-title-block':['danger-title-block', 'block'],
'dedication-block':['dedication-block', 'block'],
'dedication-paragraph-block':['dedication-paragraph-block', 'block'],
'dedication-title-block':['dedication-title-block', 'block'],
'default-admonition-outer-block':['default-admonition-outer-block', 'block'],
'default-admonition-title-block':['default-admonition-title-block', 'block'],
'default-cell':['default-cell', 'cell'],
'default-flow':['default-flow', 'flow'],
'default-footnote-label-inline':['default-footnote-label-inline', 'inline'],
'default-page-sequence':['default-page-sequence', 'page-sequence'],
'default-section-title-block':['default-section-title-block', 'block'],
'default-simple-page-master':['default-simple-page-master', 'simple-page-master'],
'definition-first-paragraph-block':['definition-first-paragraph-block', 'block'],
'definition-list-block':['definition-list-block', 'list-block'],
'definition-list-item-block':['definition-list-item-block', 'block'],
'definition-list-item-first-block':['definition-list-item-first-block', 'block'],
'definition-paragraph-block':['definition-paragraph-block', 'block'],
'definition-term-block':['definition-term-block', 'block'],
'definition-term-inline':['definition-term-inline', 'inline'],
'document-subtitle-block':['document-subtitle-block', 'block'],
'document-title-block':['document-title-block', 'block'],
'document-title-page-block':['document-title-page-block', 'block'],
'emphasis-inline':['emphasis-inline', 'inline'],
'endnote-block':['endnote-block', 'block'],
'endnote-first-block':['endnote-first-block', 'block'],
'endnotes-block':['endnotes-block', 'block'],
'endnotes-title-block':['endnotes-title-block', 'block'],
'enumerated-first-list-item':['enumerated-first-list-item', 'list-item'],
'enumerated-level2-list-block':['enumerated-level2-list-block', 'list-block'],
'enumerated-list-block':['enumerated-list-block', 'list-block'],
'enumerated-list-item':['enumerated-list-item', 'list-item'],
'enumerated-list-item-body':['enumerated-list-item-body', 'item-body'],
'enumerated-list-item-body-block':['enumerated-list-item-body-block', 'block'],
'enumerated-list-item-label':['enumerated-list-item-label', 'item-label'],
'epigraph-attribution-block':['epigraph-attribution-block', 'block'],
'epigraph-first-paragraph-block':['epigraph-first-paragraph-block', 'block'],
'epigraph-outer-block':['epigraph-outer-block', 'block'],
'epigraph-paragraph-block':['epigraph-paragraph-block', 'block'],
'error-block':['error-block', 'block'],
'error-title-block':['error-title-block', 'block'],
'even-simple-page-master':['even-simple-page-master', 'simple-page-master'],
'field-body-block':['field-body-block', 'block'],
'field-first-list-item':['field-first-list-item', 'list-item'],
'field-list-block':['field-list-block', 'list-block'],
'field-list-item':['field-list-item', 'list-item'],
'field-list-item-body':['field-list-item-body', 'item-body'],
'field-list-item-label':['field-list-item-label', 'item-label'],
'field-list-item-label-block':['field-list-item-label-block', 'block'],
'figure-block':['figure-block', 'block'],
'figure-caption-block':['figure-caption-block', 'block'],
'figure-legend-block':['figure-legend-block', 'block'],
'first-paragraph-block':['first-paragraph-block', 'bold'],
'first-simple-page-master':['first-simple-page-master', 'simple-page-master'],
'footer-block':['footer-block', 'block'],
'footer-first-block':['footer-first-block', 'block'],
'footer-region-after':['footer-region-after', 'region-after'],
'footer-second-block':['footer-second-block', 'block'],
'footer-third-block':['footer-third-block', 'block'],
'footnote':['footnote', 'footnote'],
'footnote-body':['footnote-body', 'footnote-body'],
'footnote-body-label-inline':['footnote-body-label-inline', 'inline'],
'footnote-first-paragraph-block':['footnote-first-paragraph-block', 'block'],
'footnote-item-body':['footnote-item-body', 'item-body'],
'footnote-item-label':['footnote-item-label', 'item-label'],
'footnote-label-block':['footnote-label-block', 'block'],
'footnote-label-inline':['footnote-label-inline', 'inline'],
'footnote-list-block':['footnote-list-block', 'list-block'],
'footnote-paragraph-block':['footnote-paragraph-block', 'block'],
'footnote-separator-block':['footnote-separator-block', 'block'],
'footnote-separator-flow':['footnote-separator-flow', 'flow'],
'front-body-simple-page-master':['front-body-simple-page-master', 'simple-page-master'],
'front-even-simple-page-master':['front-even-simple-page-master', 'simple-page-master'],
'front-first-simple-page-master':['front-first-simple-page-master', 'simple-page-master'],
'front-flow':['front-flow', 'flow'],
'front-matter-region-body':['front-matter-region-body', 'region-body'],
'front-odd-simple-page-master':['front-odd-simple-page-master', 'simple-page-master'],
'front-page-sequence':['front-page-sequence', 'page-sequence'],
'front-simple-page-master':['front-simple-page-master', 'simple-page-master'],
'header-block':['header-block', 'block'],
'header-first-block':['header-first-block', 'block'],
'header-region-before':['header-region-before', 'region-before'],
'header-second-block':['header-second-block', 'block'],
'header-third-block':['header-third-block', 'block'],
'highlights-first-paragraph-block':['highlights-first-paragraph-block', 'block'],
'highlights-outer-block':['highlights-outer-block', 'block'],
'highlights-paragraph-block':['highlights-paragraph-block', 'block'],
'hint-block':['hint-block', 'block'],
'hint-title-block':['hint-title-block', 'block'],
'image-block':['image-block', 'block'],
'important-block':['important-block', 'block'],
'important-title-block':['important-title-block', 'block'],
'legend-first-paragraph-block':['legend-first-paragraph-block', 'block'],
'legend-paragraph-block':['legend-paragraph-block', 'block'],
'level1-line-block':['level1-line-block', 'block'],
'level2-line-block':['level2-line-block', 'block'],
'level3-line-block':['level3-line-block', 'block'],
'level4-line-block':['level4-line-block', 'block'],
'level5-line-block':['level5-line-block', 'block'],
'literal-block':['literal-block', 'block'],
'literal-inline':['literal-inline', 'inline'],
'note-block':['note-block', 'block'],
'note-title-block':['note-title-block', 'block'],
'odd-simple-page-master':['odd-simple-page-master', 'simple-page-master'],
'option-argument-inline':['option-argument-inline', 'inline'],
'option-first-list-item':['option-first-list-item', 'list-item'],
'option-group-block':['option-group-block', 'block'],
'option-inline':['option-inline', 'inline'],
'option-list-block':['option-list-block', 'list-block'],
'option-list-definition-block':['option-list-definition-block', 'block'],
'option-list-description-block':['option-list-description-block', 'block'],
'option-list-description-first-block':['option-list-description-first-block', 'block'],
'option-list-first-item-block':['option-list-first-item-block', 'block'],
'option-list-item':['option-list-item', 'list-item'],
'option-list-item-block':['option-list-item-block', 'block'],
'option-list-item-body':['option-list-item-body', 'item-body'],
'option-list-item-body-block':['option-list-item-body-block', 'block'],
'option-list-item-label':['option-list-item-label', 'item-label'],
'option-list-item-label-block':['option-list-item-label-block', 'block'],
'outer-line-block':['outer-line-block', 'block'],
'paper-size-simple-page-master':['paper-size-simple-page-master', 'simple-page-master'],
'paragraph-block':['paragraph-block', 'block'],
'pull-quote-attribution-block':['pull-quote-attribution-block', 'block'],
'pull-quote-first-paragraph-block':['pull-quote-first-paragraph-block', 'block'],
'pull-quote-outer-block':['pull-quote-outer-block', 'block'],
'pull-quote-paragraph-block':['pull-quote-paragraph-block', 'block'],
'region-body':['region-body', 'region-body'],
'rubric-block':['rubric-block', 'block'],
'sidebar-block':['sidebar-block', 'block'],
'sidebar-first-paragraph-block':['sidebar-first-paragraph-block', 'block'],
'sidebar-paragraph-block':['sidebar-paragraph-block', 'block'],
'sidebar-subtitle-block':['sidebar-subtitle-block', 'block'],
'sidebar-title-block':['sidebar-title-block', 'block'],
'simple-page-master':['simple-page-master', 'simple-page-master'],
'strong-inline':['strong-inline', 'inline'],
'table':['table', 'table'],
'table-block-container':['table-block-container', 'block-container'],
'table-body':['table-body', 'table-body'],
'table-cell':['table-cell', 'cell'],
'table-row':['table-row', 'table-row'],
'thead-block':['thead-block', 'block'],
'thead-borderless-cell':['thead-borderless-cell', 'cell'],
'thead-cell':['thead-cell', 'cell'],
'thead-header':['thead-header', 'header'],
'tip-block':['tip-block', 'block'],
'tip-title-block':['tip-title-block', 'block'],
'title-level1-block':['title-level1-block', 'block'],
'title-level2-block':['title-level2-block', 'block'],
'title-level3-block':['title-level3-block', 'block'],
'title-level4-block':['title-level4-block', 'block'],
'title-level5-block':['title-level5-block', 'block'],
'title-level6-block':['title-level6-block', 'block'],
'title-level7-block':['title-level7-block', 'block'],
'title-level8-block':['title-level8-block', 'block'],
'title-level9-block':['title-level9-block', 'block'],
'title-number-inline':['title-number-inline', 'inline'],
'title-reference-inline':['title-reference-inline', 'inline'],
'toc-body-simple-page-master':['toc-body-simple-page-master', 'simple-page-master'],
'toc-entry-defaults-block':['toc-entry-defaults-block', 'block'],
'toc-even-simple-page-master':['toc-even-simple-page-master', 'simple-page-master'],
'toc-first-simple-page-master':['toc-first-simple-page-master', 'simple-page-master'],
'toc-flow':['toc-flow', 'flow'],
'toc-level1-block':['toc-level1-block', 'block'],
'toc-level2-block':['toc-level2-block', 'block'],
'toc-level3-block':['toc-level3-block', 'block'],
'toc-level4-block':['toc-level4-block', 'block'],
'toc-level5-block':['toc-level5-block', 'block'],
'toc-odd-simple-page-master':['toc-odd-simple-page-master', 'simple-page-master'],
'toc-page-sequence':['toc-page-sequence', 'page-sequence'],
'toc-simple-page-master':['toc-simple-page-master', 'simple-page-master'],
'toc-title-block':['toc-title-block', 'block'],
'topic-block':['topic-block', 'block'],
'topic-first-paragraph-block':['topic-first-paragraph-block', 'block'],
'topic-paragraph-block':['topic-paragraph-block', 'block'],
'topic-title-block':['topic-title-block', 'block'],
'transition-block':['transition-block', 'block'],
'warning-block':['warning-block', 'block'],
'warning-title-block':['warning-title-block', 'block'],
}

# customize
added_att_sets = {
'bullet-list':['bullet-list-block', 'list-block'], 
'document':['default-page-sequence', 'page-sequence'], 
'page':['default-simple-page-master', 'simple-page-master'], 
'even-page':['even-simple-page-master', 'simple-page-master'], 
'first-page':['first-simple-page-master', 'simple-page-master'],
'odd-page':['odd-simple-page-master', 'simple-page-master'], 
'paper-size':['paper-size-simple-page-master', 'simple-page-master'], 
'paragraph':['paragraph-block', 'block'], 
'first-paragraph':['first-paragraph-block', 'block'], 
'body':['default-flow', 'flow'],
}

att_set_dict.update(added_att_sets)


block_dict = {
'azimuth' : 'azimuth',
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-repeat' : 'background-repeat',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'border-after-color' : 'border-after-color',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-end-color' : 'border-end-color',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-start-color' : 'border-start-color',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'bottom' : 'bottom',
'break-after' : 'break-after',
'break-before' : 'break-before',
'color' : 'color',
'country' : 'country',
'cue-after' : 'cue-after',
'cue-before' : 'cue-before',
'elevation' : 'elevation',
'end-indent' : 'end-indent',
'font-family' : 'font-family',
'font-selection-strategy' : 'font-selection-strategy',
'font-size' : 'font-size',
'font-size-adjust' : 'font-size-adjust',
'font-stretch' : 'font-stretch',
'font-style' : 'font-style',
'font-variant' : 'font-variant',
'font-weight' : 'font-weight',
'hyphenate' : 'hyphenate',
'hyphenation-character' : 'hyphenation-character',
'hyphenation-keep' : 'hyphenation-keep',
'hyphenation-ladder-count' : 'hyphenation-ladder-count',
'hyphenation-push-character-count' : 'hyphenation-push-character-count',
'hyphenation-remain-character-count' : 'hyphenation-remain-character-count',
'id' : 'id',
'intrusion-displace' : 'intrusion-displace',
'keep-together' : 'keep-together',
'keep-with-next' : 'keep-with-next',
'keep-with-previous' : 'keep-with-previous',
'language' : 'language',
'last-line-end-indent' : 'last-line-end-indent',
'left' : 'left',
'linefeed-treatment' : 'linefeed-treatment',
'line-height' : 'line-height',
'line-height-shift-adjustment' : 'line-height-shift-adjustment',
'line-stacking-strategy' : 'line-stacking-strategy',
'margin-bottom' : 'margin-bottom',
'margin-left' : 'margin-left',
'margin-right' : 'margin-right',
'margin-top' : 'margin-top',
'orphans' : 'orphans',
'padding-after' : 'padding-after',
'padding-before' : 'padding-before',
'padding-bottom' : 'padding-bottom',
'padding-end' : 'padding-end',
'padding-left' : 'padding-left',
'padding-right' : 'padding-right',
'padding-start' : 'padding-start',
'padding-top' : 'padding-top',
'pause-after' : 'pause-after',
'pause-before' : 'pause-before',
'pitch' : 'pitch',
'pitch-range' : 'pitch-range',
'play-during' : 'play-during',
'relative-position' : 'relative-position',
'richness' : 'richness',
'right' : 'right',
'role' : 'role',
'script' : 'script',
'source-document' : 'source-document',
'space-after' : 'space-after',
'space-before' : 'space-before',
'span' : 'span',
'speak' : 'speak',
'speak-header' : 'speak-header',
'speak-numeral' : 'speak-numeral',
'speak-punctuation' : 'speak-punctuation',
'speech-rate' : 'speech-rate',
'start-indent' : 'start-indent',
'stress' : 'stress',
'text-align' : 'text-align',
'text-align-last' : 'text-align-last',
'text-altitude' : 'text-altitude',
'text-depth' : 'text-depth',
'text-indent' : 'text-indent',
'top' : 'top',
'visibility' : 'visibility',
'voice-family' : 'voice-family',
'volume' : 'volume',
'white-space-collapse' : 'white-space-collapse',
'white-space-treatment' : 'white-space-treatment',
'widows' : 'widows',
'wrap-option' : 'wrap-option',
}

block_container_dict = {
'absolute-position' : 'absolute-position',
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'background-repeat' : 'background-repeat',
'border-after-color' : 'border-after-color',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-end-color' : 'border-end-color',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-start-color' : 'border-start-color',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'bottom' : 'bottom',
'break-after' : 'break-after',
'break-before' : 'break-before',
'clip' : 'clip',
'display-align' : 'display-align',
'end-indent' : 'end-indent',
'height' : 'height',
'id' : 'id',
'inline-progression-dimension' : 'inline-progression-dimension',
'intrusion-displace' : 'intrusion-displace',
'keep-together' : 'keep-together',
'keep-with-next' : 'keep-with-next',
'keep-with-previous' : 'keep-with-previous',
'left' : 'left',
'margin-bottom' : 'margin-bottom',
'margin-left' : 'margin-left',
'margin-right' : 'margin-right',
'margin-top' : 'margin-top',
'overflow' : 'overflow',
'padding-after' : 'padding-after',
'padding-before' : 'padding-before',
'padding-bottom' : 'padding-bottom',
'padding-end' : 'padding-end',
'padding-left' : 'padding-left',
'padding-right' : 'padding-right',
'padding-start' : 'padding-start',
'padding-top' : 'padding-top',
'reference-orientation' : 'reference-orientation',
'right' : 'right',
'space-after' : 'space-after',
'space-before' : 'space-before',
'span' : 'span',
'start-indent' : 'start-indent',
'top' : 'top',
'width' : 'width',
'writing-mode' : 'writing-mode',
'z-index' : 'z-index',
}

cell_dict = {
'azimuth' : 'azimuth',
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'background-repeat' : 'background-repeat',
'block-progression-dimension' : 'block-progression-dimension',
'border-after-color' : 'border-after-color',
'border-after-precedence' : 'border-after-precedence',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-precedence' : 'border-before-precedence',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-end-color' : 'border-end-color',
'border-end-precedence' : 'border-end-precedence',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-start-color' : 'border-start-color',
'border-start-precedence' : 'border-start-precedence',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'bottom' : 'bottom',
'column-number' : 'column-number',
'cue-after' : 'cue-after',
'cue-before' : 'cue-before',
'display-align' : 'display-align',
'elevation' : 'elevation',
'empty-cells' : 'empty-cells',
'ends-row' : 'ends-row',
'height' : 'height',
'id' : 'id',
'inline-progression-dimension' : 'inline-progression-dimension',
'left' : 'left',
'number-columns-spanned' : 'number-columns-spanned',
'number-rows-spanned' : 'number-rows-spanned',
'padding-after' : 'padding-after',
'padding-before' : 'padding-before',
'padding-bottom' : 'padding-bottom',
'padding-end' : 'padding-end',
'padding-left' : 'padding-left',
'padding-right' : 'padding-right',
'padding-start' : 'padding-start',
'padding-top' : 'padding-top',
'pause-after' : 'pause-after',
'pause-before' : 'pause-before',
'pitch' : 'pitch',
'pitch-range' : 'pitch-range',
'play-during' : 'play-during',
'relative-position' : 'relative-position',
'richness' : 'richness',
'right' : 'right',
'role' : 'role',
'source-document' : 'source-document',
'speak' : 'speak',
'speak-header' : 'speak-header',
'speak-numeral' : 'speak-numeral',
'speak-punctuation' : 'speak-punctuation',
'speech-rate' : 'speech-rate',
'starts-row' : 'starts-row',
'stress' : 'stress',
'top' : 'top',
'voice-family' : 'voice-family',
'volume' : 'volume',
'width' : 'width',
}

flow_dict = {'flow-name': 'flow-name'}


footnote_dict = {'role': 'role', 'source-document': 'source-document'}
footnote_body_dict = {}
footnote_body_dict.update(footnote_dict)

header_dict = {
'azimuth' : 'azimuth',
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'background-repeat' : 'background-repeat',
'border-after-color' : 'border-after-color',
'border-after-precedence' : 'border-after-precedence',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-precedence' : 'border-before-precedence',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-collapse' : 'border-collapse',
'border-end-color' : 'border-end-color',
'border-end-precedence' : 'border-end-precedence',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-separation' : 'border-separation',
'border-start-color' : 'border-start-color',
'border-start-precedence' : 'border-start-precedence',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'bottom' : 'bottom',
'cue-after' : 'cue-after',
'cue-before' : 'cue-before',
'elevation' : 'elevation',
'id' : 'id',
'left' : 'left',
'pause-after' : 'pause-after',
'pause-before' : 'pause-before',
'pitch' : 'pitch',
'pitch-range' : 'pitch-range',
'play-during' : 'play-during',
'relative-position' : 'relative-position',
'richness' : 'richness',
'right' : 'right',
'role' : 'role',
'source-document' : 'source-document',
'speak' : 'speak',
'speak-header' : 'speak-header',
'speak-numeral' : 'speak-numeral',
'speak-punctuation' : 'speak-punctuation',
'speech-rate' : 'speech-rate',
'stress' : 'stress',
'top' : 'top',
'visibility' : 'visibility',
'voice-family' : 'voice-family',
'volume' : 'volume',
}


inline_dict = {
'alignment-adjust' : 'alignment-adjust',
'alignment-baseline' : 'alignment-baseline',
'azimuth' : 'azimuth',
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'background-repeat' : 'background-repeat',
'baseline-shift' : 'baseline-shift',
'block-progression-dimension' : 'block-progression-dimension',
'border-after-color' : 'border-after-color',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-end-color' : 'border-end-color',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-start-color' : 'border-start-color',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'bottom' : 'bottom',
'color' : 'color',
'cue-after' : 'cue-after',
'cue-before' : 'cue-before',
'dominant-baseline' : 'dominant-baseline',
'elevation' : 'elevation',
'font-family' : 'font-family',
'font-selection-strategy' : 'font-selection-strategy',
'font-size' : 'font-size',
'font-size-adjust' : 'font-size-adjust',
'font-stretch' : 'font-stretch',
'font-style' : 'font-style',
'font-variant' : 'font-variant',
'font-weight' : 'font-weight',
'height' : 'height',
'id' : 'id',
'inline-progression-dimension' : 'inline-progression-dimension',
'keep-together' : 'keep-together',
'keep-with-next' : 'keep-with-next',
'keep-with-previous' : 'keep-with-previous',
'left' : 'left',
'line-height' : 'line-height',
'margin-bottom' : 'margin-bottom',
'margin-left' : 'margin-left',
'margin-right' : 'margin-right',
'margin-top' : 'margin-top',
'padding-after' : 'padding-after',
'padding-before' : 'padding-before',
'padding-bottom' : 'padding-bottom',
'padding-end' : 'padding-end',
'padding-left' : 'padding-left',
'padding-right' : 'padding-right',
'padding-start' : 'padding-start',
'padding-top' : 'padding-top',
'pause-after' : 'pause-after',
'pause-before' : 'pause-before',
'pitch' : 'pitch',
'pitch-range' : 'pitch-range',
'play-during' : 'play-during',
'relative-position' : 'relative-position',
'richness' : 'richness',
'right' : 'right',
'role' : 'role',
'source-document' : 'source-document',
'space-end' : 'space-end',
'space-start' : 'space-start',
'speak' : 'speak',
'speak-header' : 'speak-header',
'speak-numeral' : 'speak-numeral',
'speak-punctuation' : 'speak-punctuation',
'speech-rate' : 'speech-rate',
'stress' : 'stress',
'text-decoration' : 'text-decoration',
'top' : 'top',
'visibility' : 'visibility',
'voice-family' : 'voice-family',
'volume' : 'volume',
'width' : 'width',
'wrap-option' : 'wrap-option',
}

item_body_dict = {
'Property' : 'Property',
'id' : 'id',
'keep-together' : 'keep-together',
'role' : 'role',
'source-document' : 'source-document',
}

item_label_dict = {}
item_label_dict.update(item_body_dict)

list_item_dict = {
'azimuth' : 'azimuth',
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'background-repeat' : 'background-repeat',
'border-after-color' : 'border-after-color',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-end-color' : 'border-end-color',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-start-color' : 'border-start-color',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'bottom' : 'bottom',
'break-after' : 'break-after',
'break-before' : 'break-before',
'cue-after' : 'cue-after',
'cue-before' : 'cue-before',
'elevation' : 'elevation',
'end-indent' : 'end-indent',
'id' : 'id',
'intrusion-displace' : 'intrusion-displace',
'keep-together' : 'keep-together',
'keep-with-next' : 'keep-with-next',
'keep-with-previous' : 'keep-with-previous',
'left' : 'left',
'margin-bottom' : 'margin-bottom',
'margin-left' : 'margin-left',
'margin-right' : 'margin-right',
'margin-top' : 'margin-top',
'padding-after' : 'padding-after',
'padding-before' : 'padding-before',
'padding-bottom' : 'padding-bottom',
'padding-end' : 'padding-end',
'padding-left' : 'padding-left',
'padding-right' : 'padding-right',
'padding-start' : 'padding-start',
'padding-top' : 'padding-top',
'pause-after' : 'pause-after',
'pause-before' : 'pause-before',
'pitch' : 'pitch',
'pitch-range' : 'pitch-range',
'play-during' : 'play-during',
'relative-align' : 'relative-align',
'relative-position' : 'relative-position',
'richness' : 'richness',
'right' : 'right',
'role' : 'role',
'source-document' : 'source-document',
'space-after' : 'space-after',
'space-before' : 'space-before',
'speak' : 'speak',
'speak-header' : 'speak-header',
'speak-numeral' : 'speak-numeral',
'speak-punctuation' : 'speak-punctuation',
'speech-rate' : 'speech-rate',
'start-indent' : 'start-indent',
'stress' : 'stress',
'top' : 'top',
'voice-family' : 'voice-family',
'volume' : 'volume',
}

list_block_dict = {
'azimuth' : 'azimuth',
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'background-repeat' : 'background-repeat',
'border-after-color' : 'border-after-color',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-end-color' : 'border-end-color',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-start-color' : 'border-start-color',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'bottom' : 'bottom',
'break-after' : 'break-after',
'break-before' : 'break-before',
'cue-after' : 'cue-after',
'cue-before' : 'cue-before',
'elevation' : 'elevation',
'end-indent' : 'end-indent',
'id' : 'id',
'intrusion-displace' : 'intrusion-displace',
'keep-together' : 'keep-together',
'keep-with-next' : 'keep-with-next',
'keep-with-previous' : 'keep-with-previous',
'left' : 'left',
'margin-bottom' : 'margin-bottom',
'margin-left' : 'margin-left',
'margin-right' : 'margin-right',
'margin-top' : 'margin-top',
'padding-after' : 'padding-after',
'padding-before' : 'padding-before',
'padding-bottom' : 'padding-bottom',
'padding-end' : 'padding-end',
'padding-left' : 'padding-left',
'padding-right' : 'padding-right',
'padding-start' : 'padding-start',
'padding-top' : 'padding-top',
'pause-after' : 'pause-after',
'pause-before' : 'pause-before',
'pitch' : 'pitch',
'pitch-range' : 'pitch-range',
'play-during' : 'play-during',
'provisional-distance-between-starts' : 'provisional-distance-between-starts',
'provisional-label-separation' : 'provisional-label-separation',
'relative-position' : 'relative-position',
'richness' : 'richness',
'right' : 'right',
'role' : 'role',
'source-document' : 'source-document',
'space-after' : 'space-after',
'space-before' : 'space-before',
'speak' : 'speak',
'speak-header' : 'speak-header',
'speak-numeral' : 'speak-numeral',
'speak-punctuation' : 'speak-punctuation',
'speech-rate' : 'speech-rate',
'start-indent' : 'start-indent',
'stress' : 'stress',
'top' : 'top',
'voice-family' : 'voice-family',
'volume' : 'volume',
}

page_sequence_dict = {
'Property' : 'Property',
'country' : 'country',
'force-page-count' : 'force-page-count',
'format' : 'format',
'grouping-separator' : 'grouping-separator',
'grouping-size' : 'grouping-size',
'id' : 'id',
'initial-page-number' : 'initial-page-number',
'language' : 'language',
'letter-value' : 'letter-value',
'master-reference' : 'master-reference',
}


region_after_dict = {
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'background-repeat' : 'background-repeat',
'border-after-color' : 'border-after-color',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-end-color' : 'border-end-color',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-start-color' : 'border-start-color',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'clip' : 'clip',
'display-align' : 'display-align',
'extent' : 'extent',
'overflow' : 'overflow',
'padding-after' : 'padding-after',
'padding-before' : 'padding-before',
'padding-bottom' : 'padding-bottom',
'padding-end' : 'padding-end',
'padding-left' : 'padding-left',
'padding-right' : 'padding-right',
'padding-start' : 'padding-start',
'padding-top' : 'padding-top',
'precedence' : 'precedence',
'reference-orientation' : 'reference-orientation',
'region-name' : 'region-name',
'writing-mode' : 'writing-mode',
}

region_before_dict = { }
region_before_dict.update(region_after_dict)

# very close to region_after_dict
region_body_dict = {
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'background-repeat' : 'background-repeat',
'border-after-color' : 'border-after-color',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-end-color' : 'border-end-color',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-start-color' : 'border-start-color',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'clip' : 'clip',
'column-count' : 'column-count',
'column-gap' : 'column-gap',
'display-align' : 'display-align',
'end-indent' : 'end-indent',
'margin-bottom' : 'margin-bottom',
'margin-left' : 'margin-left',
'margin-right' : 'margin-right',
'margin-top' : 'margin-top',
'overflow' : 'overflow',
'padding-after' : 'padding-after',
'padding-before' : 'padding-before',
'padding-bottom' : 'padding-bottom',
'padding-end' : 'padding-end',
'padding-left' : 'padding-left',
'padding-right' : 'padding-right',
'padding-start' : 'padding-start',
'padding-top' : 'padding-top',
'reference-orientation' : 'reference-orientation',
'region-name' : 'region-name',
'space-after' : 'space-after',
'space-before' : 'space-before',
'writing-mode' : 'writing-mode',
}

simple_page_master_dict = {
'end-indent' : 'end-indent',
'margin-bottom' : 'margin-bottom',
'margin-left' : 'margin-left',
'margin-right' : 'margin-right',
'margin-top' : 'margin-top',
'master-name' : 'master-name',
'page-height' : 'page-height',
'height' : 'page-height',
'page-width' : 'page-width',
'width' : 'page-width',
'reference-orientation' : 'reference-orientation',
'space-after' : 'space-after',
'space-before' : 'space-before',
'start-indent' : 'start-indent',
'writing-mode' : 'writing-mode',
'bottom-margin' : 'margin-bottom', # added
'left-margin' : 'margin-left', # added
'right-margin' : 'margin-right', # added
'top-margin' : 'margin-top', # added
}

table_body_dict = {
'azimuth' : 'azimuth',
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'background-repeat' : 'background-repeat',
'border-after-color' : 'border-after-color',
'border-after-precedence' : 'border-after-precedence',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-precedence' : 'border-before-precedence',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-collapse' : 'border-collapse',
'border-end-color' : 'border-end-color',
'border-end-precedence' : 'border-end-precedence',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-separation' : 'border-separation',
'border-start-color' : 'border-start-color',
'border-start-precedence' : 'border-start-precedence',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'bottom' : 'bottom',
'cue-after' : 'cue-after',
'cue-before' : 'cue-before',
'elevation' : 'elevation',
'id' : 'id',
'left' : 'left',
'pause-after' : 'pause-after',
'pause-before' : 'pause-before',
'pitch' : 'pitch',
'pitch-range' : 'pitch-range',
'play-during' : 'play-during',
'relative-position' : 'relative-position',
'richness' : 'richness',
'right' : 'right',
'role' : 'role',
'source-document' : 'source-document',
'speak' : 'speak',
'speak-header' : 'speak-header',
'speak-numeral' : 'speak-numeral',
'speak-punctuation' : 'speak-punctuation',
'speech-rate' : 'speech-rate',
'stress' : 'stress',
'top' : 'top',
'visibility' : 'visibility',
'voice-family' : 'voice-family',
'volume' : 'volume',
}

table_dict = {
'azimuth' : 'azimuth',
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'background-repeat' : 'background-repeat',
'block-progression-dimension' : 'block-progression-dimension',
'border-after-color' : 'border-after-color',
'border-after-precedence' : 'border-after-precedence',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-precedence' : 'border-before-precedence',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-collapse' : 'border-collapse',
'border-end-color' : 'border-end-color',
'border-end-precedence' : 'border-end-precedence',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-separation' : 'border-separation',
'border-start-color' : 'border-start-color',
'border-start-precedence' : 'border-start-precedence',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'bottom' : 'bottom',
'break-after' : 'break-after',
'break-before' : 'break-before',
'cue-after' : 'cue-after',
'cue-before' : 'cue-before',
'elevation' : 'elevation',
'end-indent' : 'end-indent',
'height' : 'height',
'id' : 'id',
'inline-progression-dimension' : 'inline-progression-dimension',
'intrusion-displace' : 'intrusion-displace',
'keep-together' : 'keep-together',
'keep-with-next' : 'keep-with-next',
'keep-with-previous' : 'keep-with-previous',
'left' : 'left',
'margin-bottom' : 'margin-bottom',
'margin-left' : 'margin-left',
'margin-right' : 'margin-right',
'margin-top' : 'margin-top',
'padding-after' : 'padding-after',
'padding-before' : 'padding-before',
'padding-bottom' : 'padding-bottom',
'padding-end' : 'padding-end',
'padding-left' : 'padding-left',
'padding-right' : 'padding-right',
'padding-start' : 'padding-start',
'padding-top' : 'padding-top',
'pause-after' : 'pause-after',
'pause-before' : 'pause-before',
'pitch' : 'pitch',
'pitch-range' : 'pitch-range',
'play-during' : 'play-during',
'relative-position' : 'relative-position',
'richness' : 'richness',
'right' : 'right',
'role' : 'role',
'source-document' : 'source-document',
'space-after' : 'space-after',
'space-before' : 'space-before',
'speak' : 'speak',
'speak-header' : 'speak-header',
'speak-numeral' : 'speak-numeral',
'speak-punctuation' : 'speak-punctuation',
'speech-rate' : 'speech-rate',
'start-indent' : 'start-indent',
'stress' : 'stress',
'table-layout' : 'table-layout',
'table-omit-footer-at-break' : 'table-omit-footer-at-break',
'table-omit-header-at-break' : 'table-omit-header-at-break',
'top' : 'top',
'voice-family' : 'voice-family',
'volume' : 'volume',
'width' : 'width',
'writing-mode' : 'writing-mode',
}

table_row_dict = {
'azimuth' : 'azimuth',
'background-attachment' : 'background-attachment',
'background-color' : 'background-color',
'background-image' : 'background-image',
'background-position-horizontal' : 'background-position-horizontal',
'background-position-vertical' : 'background-position-vertical',
'background-repeat' : 'background-repeat',
'block-progression-dimension' : 'block-progression-dimension',
'border-after-color' : 'border-after-color',
'border-after-precedence' : 'border-after-precedence',
'border-after-style' : 'border-after-style',
'border-after-width' : 'border-after-width',
'border-before-color' : 'border-before-color',
'border-before-precedence' : 'border-before-precedence',
'border-before-style' : 'border-before-style',
'border-before-width' : 'border-before-width',
'border-bottom-color' : 'border-bottom-color',
'border-bottom-style' : 'border-bottom-style',
'border-bottom-width' : 'border-bottom-width',
'border-collapse' : 'border-collapse',
'border-end-color' : 'border-end-color',
'border-end-precedence' : 'border-end-precedence',
'border-end-style' : 'border-end-style',
'border-end-width' : 'border-end-width',
'border-left-color' : 'border-left-color',
'border-left-style' : 'border-left-style',
'border-left-width' : 'border-left-width',
'border-right-color' : 'border-right-color',
'border-right-style' : 'border-right-style',
'border-right-width' : 'border-right-width',
'border-separation' : 'border-separation',
'border-start-color' : 'border-start-color',
'border-start-precedence' : 'border-start-precedence',
'border-start-style' : 'border-start-style',
'border-start-width' : 'border-start-width',
'border-top-color' : 'border-top-color',
'border-top-style' : 'border-top-style',
'border-top-width' : 'border-top-width',
'bottom' : 'bottom',
'break-after' : 'break-after',
'break-before' : 'break-before',
'cue-after' : 'cue-after',
'cue-before' : 'cue-before',
'elevation' : 'elevation',
'height' : 'height',
'id' : 'id',
'keep-together' : 'keep-together',
'keep-with-next' : 'keep-with-next',
'keep-with-previous' : 'keep-with-previous',
'left' : 'left',
'pause-after' : 'pause-after',
'pause-before' : 'pause-before',
'pitch' : 'pitch',
'pitch-range' : 'pitch-range',
'play-during' : 'play-during',
'relative-position' : 'relative-position',
'richness' : 'richness',
'right' : 'right',
'role' : 'role',
'source-document' : 'source-document',
'speak' : 'speak',
'speak-header' : 'speak-header',
'speak-numeral' : 'speak-numeral',
'speak-punctuation' : 'speak-punctuation',
'speech-rate' : 'speech-rate',
'stress' : 'stress',
'top' : 'top',
'visibility' : 'visibility',
'voice-family' : 'voice-family',
'volume' : 'volume',
}

# block_dict.update({'font-style': ['font-style']})
# inline_dict.update({'font-style': ['font-style']})

# customize
font_dict = { 'font': 'font-family', }
line_height_dict = {'line-spacing':'line-height'}
page_sequence_dict.update(font_dict)
page_sequence_dict.update({'font-size':'font-size'})
block_dict.update(font_dict)
inline_dict.update(font_dict)
block_dict.update(line_height_dict)
inline_dict.update(line_height_dict)
flow_dict.update(line_height_dict)

block_set = set(block_dict.keys())
block_container_set = set(block_container_dict.keys())
cell_set= set(cell_dict.keys())
intersect_block_block_container = block_set.intersection(block_container_set)
intersect_block_container_cell = block_container_set.intersection(cell_set)
diff = block_container_set.symmetric_difference(block_set)

rbe_set = set(region_before_dict.keys())
rbo_set = set(region_body_dict.keys())
diff = rbe_set.symmetric_difference(rbo_set)

font_style_dict={'bold': [('font-weight','bold')],
'italic': [('font-style','italic')],
'bold-italic':[('font-weight','bold'), ('font-style','italic')],
'italic-bold':[('font-weight','bold'), ('font-style','italic')]
}
special_values_dict = {'font-style':[True],
        }

special_atts_dict = {
        'header':[True],
        'footer':[True],
        }



which_dict = {
'block': block_dict,
'block-container': block_container_dict,
'cell': cell_dict,
'flow': flow_dict,
'footnote-body': footnote_body_dict,
'header': header_dict,
'inline': inline_dict,
'item-body': item_body_dict,
'item-label': item_label_dict,
'list-block':list_block_dict,
'list-item': list_item_dict,
'page-sequence': page_sequence_dict,
'region-after': region_after_dict,
'region-before': region_before_dict,
'region-body': region_body_dict,
'simple-page-master': simple_page_master_dict,
'table': table_dict,
'table-body': table_body_dict,
'table-row': table_row_dict,
}

prop_as_param_dict = {
'page.page-layout':'page-layout',
}

param_dict = {
'abstract-pagination' : 'with-front',
'address-text' : 'Address: ',
'attention-title' : 'Attention!',
'author-text' : 'Author: ',
'authors-text' : 'Authors: ',
'bibliographic-pagination' : 'with-toc',
'bullet-text' : '•',
'caution-title' : 'Caution!',
'contact-text' : 'Contact: ',
'copyright-text' : 'Copyright: ',
'danger-title' : '!Danger!',
'date-text' : 'Date: ',
'dedication-pagination' : 'with-front',
'error-title' : 'Error',
'footnote-placement' : 'footnote',
'footnote-style' : 'list',
'front-order' : 'title,bibliographic,dedication,abstract,toc',
'hint-title' : 'Hint',
'important-title' : 'Important',
'inherit-section-num' : 'True',
'internal-link-type' : 'link',
'note-title' : 'Note',
'number-section1' : '1',
'number-section2' : '.1',
'number-section3' : '.1',
'number-section4' : '.1',
'number-section5' : '.1',
'number-section6' : '.1',
'number-section7' : '.1',
'number-section8' : '.1',
'number-section9' : '.1',
'number-verse' : '',
'option-list-format' : 'list',
'options-separator' : ', ',
'organization-text' : 'Organization: ',
'page-layout' : 'simple',
'revision-text' : 'Revision: ',
'space-between-footnotes' : '5pt',
'spacing-footer' : '',
'spacing-header' : '',
'status-text' : 'Status: ',
'strict' : '',
'suppress-first-page-footer' : '',
'suppress-first-page-header' : '',
'table-title-placement' : 'bottom',
'test' : '',
'text-before-block-quote-attribution' : '—',
'text-before-epigraph-attribution' : '—',
'text-before-pull-quote-attribution' : '—',
'tip-title' : 'Tip',
'title-pagination' : 'with-front',
'toc-pagination' : 'with-toc',
'transition-text' : '***',
'version-text' : 'Version: ',
'warning-title' : 'Warning!',
}
param_list = param_dict.keys()

commands_list = ['xsl-stylesheet']
