= Functional tests
# Note: command lines are implicitly tested.
+ Title lines
  (echo = This is a title line; cat cmds.txt) | gen_gress | perl -n body.prl
+ Positive tests
  (echo + Positive test; cat cmds.txt) | gen_gress | perl -n body.prl
+ Negative tests
  (echo - Negative test; cat cmds.txt) | gen_gress | perl -n body.prl
+ Two title lines
  (echo = Title 1; cat cmds.txt; echo = Title 2; cat cmds.txt) | gen_gress | \
  perl -n body.prl
