#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Author: Felix Wiemann
# Contact: Felix_Wiemann@ososo.de
# Revision: $Revision$
# Date: $Date$
# Copyright: This module has been placed in the public domain.

"""
Test for docutils XML writer.
"""

from __init__ import DocutilsTestSupport

import docutils
import docutils.core


class DocutilsXMLTestCase(DocutilsTestSupport.StandardTestCase):

    input = 'Test\n\n----------\n\nTest. äöü€'
    xmldecl = '<?xml version="1.0" encoding="iso-8859-1"?>\n'
    doctypedecl = '<!DOCTYPE document PUBLIC "+//IDN docutils.sourceforge.net//DTD Docutils Generic//EN//XML" "http://docutils.sourceforge.net/docs/ref/docutils.dtd">\n'
    generatedby = '<!-- Generated by Docutils %s -->\n' % docutils.__version__
    bodynormal = '<document source="&lt;string&gt;"><paragraph>Test</paragraph><transition/><paragraph>Test. \xe4\xf6\xfc&#8364;</paragraph></document>'
    bodynewlines = '<document source="&lt;string&gt;">\n<paragraph>\nTest\n</paragraph>\n<transition/>\n<paragraph>\nTest. \xe4\xf6\xfc&#8364;\n</paragraph>\n</document>\n'
    bodyindents = '<document source="&lt;string&gt;">\n    <paragraph>\n        Test\n    </paragraph>\n    <transition/>\n    <paragraph>\n        Test. \xe4\xf6\xfc&#8364;\n    </paragraph>\n</document>\n'

    def test_publish(self):
        settings = {'input_encoding': 'utf8',
                    'output_encoding': 'iso-8859-1',
                    '_disable_config': 1}
        for settings['newlines'] in 0, 1:
            for settings['indents'] in 0, 1:
                for settings['xml_declaration'] in 0, 1:
                    for settings['doctype_declaration'] in 0, 1:

                        expected = ''
                        if settings['xml_declaration']:
                            expected += self.xmldecl
                        if settings['doctype_declaration']:
                            expected += self.doctypedecl
                        expected += self.generatedby
                        if settings['indents']:
                            expected += self.bodyindents
                        elif settings['newlines']:
                            expected += self.bodynewlines
                        else:
                            expected += self.bodynormal

                        self.assertEqual(docutils.core.publish_string
                                         (source=self.input,
                                          reader_name='standalone',
                                          writer_name='docutils_xml',
                                          settings_overrides=settings),
                                         expected)


if __name__ == '__main__':
    import unittest
    unittest.main()
