### -*-makefile-*-

default: prest

.PHONY: default all prest helpers install testall test testhelpers doc clean

all: prest helpers

prest:
	cd src; make

helpers:
	cd helpers/src; make

testall: testhelpers test

test:
	cd tests; make realclean; make

testhelpers:
	cd helpers/tests; make

doc:
	cd doc/src; make

clean:
	cd tests; make clean

install:
	mkdir -p $(INSTALL_DIR)
	chmod -R +w $(INSTALL_DIR)
	cp -r bin doc/html $(INSTALL_DIR)
	chmod -R -w $(INSTALL_DIR)
