=head1 NAME

rst2graph - Generate graphs from the links in a reStructuredText file

=head1 SYNOPSIS

B<rst2graph.py> [I<options>]... [I<reST> [I<graph>]]

=head1 DESCRIPTION

Translates a reStructuredText document to a graph in various
languages. Depending on the output format this can then be transformed
to a graphic for instance by B<Graphviz>.

=head1 OPTIONS

Try

  rst2graph.py --help

for an explanation of all options.

=head1 SEE ALSO

=over 4

=item Docutils

http://docutils.sourceforge.net/

=item reStructuredText

http://docutils.sourceforge.net/rst.html

=item GXL

http://www.gupro.de/GXL

=item Graphviz

http://graphviz.org/

=back

=head1 AVAILABILITY

B<rst2graph> is available from

http://www.merten-home.de/FreeSoftware/rst2graph/

and the Docutils sandbox

svn://svn.code.sf.net/p/docutils/code/trunk/sandbox/rst2graph
