slide-shows.s5.html: slide-shows.rst
	rst2s5.py slide-shows.rst slide-shows.s5.html \
		--config ../../tools/docutils.conf \
		--overwrite-theme-files \
		--link-stylesheet \
		--no-generator --no-datestamp --no-source-link

smartquotes.html: smartquotes.rst
	rst2html.py smartquotes.rst smartquotes.html --smart-quotes=true
