GRESS_DIR = ../..

# Use the following to customize flags to gen_gress
GEN_GRESS_FLAGS = -p $(dir $(shell which perl))

GRESS_LIB = $(GRESS_DIR)/lib
GRESS_BIN = $(GRESS_DIR)/bin
include $(GRESS_LIB)/gress.mak
