#!/bin/sh

IN_DIR=input
OUT_DIR=output
EXP_DIR=expected

if [ -z "$1" ] ; then
  FILES=*.txt
else
  FILES=$1
fi

for IN_F in $IN_DIR/$FILES ; do
  BASE=`basename $IN_F`
  if [ $BASE == "tutorial.txt" -o $BASE == "reference.txt" ] ; then
    continue
  fi
  F_BASE=${BASE/.txt}
  python rst2docpy.py $IN_F $OUT_DIR/$F_BASE.tex
  diff -s -u $EXP_DIR/$F_BASE.tex $OUT_DIR/$F_BASE.tex
done


