#!/bin/sh

IN_DIR=input
OUT_DIR=output
EXP_DIR=expected

if [ -z "$1" ] ; then
  FILES=*.txt
else
  FILES=$1
fi

CMD="../../docutils/tools/rst2man.py --traceback"

for IN_F in $IN_DIR/$FILES ; do
  BASE=`basename $IN_F`
  F_BASE=${BASE%.txt}
  if echo $F_BASE | grep -q -- '-de\.' ; then
    OPT="-l de"
  else
    OPT=""
  fi
  $CMD $OPT $IN_F $OUT_DIR/$F_BASE.man
  if [ $? -eq 0 ] ; then
    diff -s -u $EXP_DIR/$F_BASE.man $OUT_DIR/$F_BASE.man
    for ENC in latin1 utf8 ascii ; do
      if [ -e $EXP_DIR/$F_BASE.$ENC ] ; then
        man -T$ENC $OUT_DIR/$F_BASE.man > $OUT_DIR/$F_BASE.$ENC
        diff -s -u $EXP_DIR/$F_BASE.$ENC $OUT_DIR/$F_BASE.$ENC
      fi
    done
  fi
done


