#!/usr/local/bin/perl

# This script simply runs the experimental version of prest in blib/scripts.

use FindBin;
eval "%CFG = (" . `cat $FindBin::RealBin/../config.log` . ")";

my @ARGS = ("-I$FindBin::RealBin/../blib/lib",
	    "$FindBin::RealBin/../blib/script/prest",
	    @ARGV);
if ($ENV{DEBUG}) {
    unshift @ARGS, '-d' ;
    push @ARGS, qw(-D no_line_directives);
}

exec $CFG{perl},@ARGS;
