#!/bin/sh

REF_DIR=test

if [ "$1" = "create" ] ; then
  CREATE=1
fi

TMPF=.diff.tmp
for F in `ls $REF_DIR/*.txt*.tex` ; do
	diff -s -u $F.ref $F > $TMPF
	if test $? -gt 0 ; then
		less $TMPF
		if [ "$CREATE" == "1" ] ; then
			mv $F $F.ref
		fi
	fi
done
rm $TMPF
