#!/bin/sh

CMD="../../tools/rst2latex.py --documentclass=book"
INF=test/README.txt
OUTF="$INF-book.tex"
REFF="$OUTF.ref"
$CMD $INF > $OUTF
diff -q -s $REFF $OUTF 
echo --------------------------

CMD="../../tools/rst2latex.py"
#CMD="../../tools/rst2latex.py --footnote-references=superscript"
#CMD="../../tools/rst2latex.py --documentclass=book --hyperlink-color=0"

if [ -z "$1" ] ; then
  FM="*.txt"
else
  FM=$1
fi

for INF in `ls test/$FM` ; do
  OUTF="$INF.tex"
  REFF="$OUTF.ref"
  $CMD $INF > $OUTF
  diff -q -s $REFF $OUTF 
  echo --------------------------
done
INF=test/tools.txt
OUTF="$INF-ltoc.tex"
REFF="$OUTF.ref"
$CMD --use-latex-toc 1 $INF > $OUTF
diff -q -s $REFF $OUTF 
echo --------------------------

CMD="../../tools/rst2latex.py -l de"
INF=test/quotes.txt
OUTF="$INF-l-de.tex"
REFF="$OUTF.ref"
$CMD $INF > $OUTF
diff -q -s $REFF $OUTF 
echo --------------------------


