#!/bin/sh

CHECKS=0
FAILS=0

function do_diff() {
  CHECKS=$((CHECKS + 1)) 
  diff -q -s $1 $2
  if test $? -gt 0 ; then
    FAILS=$((FAIL + 1)) 
  fi
}

function report() {
  echo "-------------------------------------"
  if test $FAILS -eq 0 ; then
    echo "OK: all $CHECKS tests passed"
  else
    echo "ERROR: $FAILS of $CHECKS failed"
  fi
}
#CMD="../../tools/rst2latex.py --snap-footnote-refs=1"
#CMD="../../tools/rst2latex.py --footnote-references=superscript"
#CMD="../../tools/rst2latex.py --documentclass=book --hyperlink-color=0"

CMD="../../tools/rst2latex.py"
if [ -z "$1" ] ; then
  FM="*.txt"
else
  FM=$1
fi


for INF in `ls test/$FM` ; do
  OUTF="$INF.tex"
  REFF="$OUTF.ref"
  $CMD $INF > $OUTF
  do_diff $REFF $OUTF 
done

if [ -n "$1" -a ! "$1" == "-" ] ; then
  report
  exit
fi

INF=test/kasten.txt
OUTF="$INF-de.tex"
REFF="$OUTF.ref"
$CMD -l de $INF > $OUTF
do_diff $REFF $OUTF 

INF=test/tools.txt
OUTF="$INF-ltoc.tex"
REFF="$OUTF.ref"
$CMD --use-latex-toc 1 $INF > $OUTF
do_diff $REFF $OUTF 

CMD="../../tools/rst2latex.py -l de"
INF=test/quotes.txt
OUTF="$INF-l-de.tex"
REFF="$OUTF.ref"
$CMD $INF > $OUTF
do_diff $REFF $OUTF 

# with generated footer
CMD="../../tools/rst2latex.py -gs"
INF=test/README.txt
OUTF="$INF-gs.tex"
REFF="$OUTF.ref"
$CMD $INF > $OUTF
do_diff $REFF $OUTF 

CMD="../../tools/rst2latex.py --documentclass=book"
INF=test/README.txt
OUTF="$INF-book.tex"
REFF="$OUTF.ref"
$CMD $INF > $OUTF
do_diff $REFF $OUTF 

#CMD="../../tools/rst2latex.py --dump-settings"
CMD="../../tools/rst2latex.py --no-doc-info"
INF=test/README.txt
OUTF="$INF-no-info.tex"
REFF="$OUTF.ref"
$CMD $INF > $OUTF
do_diff $REFF $OUTF 

CMD="../../tools/rst2latex.py --no-doc-title"
INF=test/README.txt
OUTF="$INF-no-title.tex"
REFF="$OUTF.ref"
$CMD $INF > $OUTF
do_diff $REFF $OUTF 

CMD="../../tools/rst2latex.py --no-doc-title --no-doc-info"
INF=test/README.txt
OUTF="$INF-no-title-info.tex"
REFF="$OUTF.ref"
$CMD $INF > $OUTF
do_diff $REFF $OUTF 

echo ATTRIBUTION
CMD="../../tools/rst2latex.py --attribution=none"
INF=test/attribution.txt
OUTF="$INF-none-attribution.tex"
REFF="$OUTF.ref"
$CMD $INF > $OUTF
do_diff $REFF $OUTF 

CMD="../../tools/rst2latex.py --attribution=parens"
INF=test/attribution.txt
OUTF="$INF-parens-attribution.tex"
REFF="$OUTF.ref"
$CMD $INF > $OUTF
do_diff $REFF $OUTF 

INF=test/iso-8859-15.txt
OUTF="$INF-enc.tex"
REFF="$OUTF.ref"
$CMD --input-encoding=iso-8859-15 --output-encoding=iso-8859-15 $INF > $OUTF
do_diff $REFF $OUTF 

report

