=head1 NAME

rstdiff - Generate a diff from two reStructuredText input files

=head1 SYNOPSIS

B<rstdiff.py> [I<options>]... I<old-reST> [I<new-reST> [I<diff-output>]]

=head1 DESCRIPTION

Generates a structural diff from two reStructuredText input documents
and produces an annotated result.

=head1 OPTIONS

Try

  rstdiff.py --help

for an explanation of all options.

=head1 SEE ALSO

=over 4

=item Docutils

http://docutils.sourceforge.net/

=item reStructuredText

http://docutils.sourceforge.net/rst.html

=back

=head1 AVAILABILITY

B<rstdiff> is available from

http://www.merten-home.de/FreeSoftware/rstdiff/

and the Docutils sandbox

svn://svn.berlios.de/docutils/trunk/sandbox/rstdiff
